spring.application.name=RentalAgent

spring.datasource.url=jdbc:postgresql://localhost:5432/rental_agent
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.conexxt-path=/RetalAgent
server.port=8080

