spring.application.name=RentalAgent

spring.datasource.url=jdbc:mysql//localhost:3306/rental_agent
spring.datasource.username=root
spring.datasource.password=Cdltibdk1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.conexxt-path=/RetalAgent
server.port=8080

